name: Chromatic

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic-deployment:
    name: Chromatic Deployment
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
          exitOnceUploaded: true
          externals: 'app/styles/tailwind.css'
        env:
          SB: 1
          API_URL: ${{ secrets.API_URL }}
          MSW_ENABLED: ${{ secrets.MSW_ENABLED }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SITE_URL: ${{ secrets.SITE_URL }}
