name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Vitest and Playwright
    if: (github.event_name == 'pull_request') && !contains(github.event.head_commit.message, 'chore:')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest tests
        run: npm run test:ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          API_URL: ${{ secrets.API_URL }}
          MSW_ENABLED: ${{ secrets.MSW_ENABLED }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SITE_URL: ${{ secrets.SITE_URL }}


